# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

   pod 'SDCycleScrollView', '~> 1.65'
   pod 'MJRefresh'


target 'FireCatLive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FireCatLive

end
